package cc.dames.jepc;

/**
 * <a href="https://www.fs-bank.de/content/dam/f1131-0/webn/sepa_mustervorlagen/uebersicht_purpose_codes.pdf">Purpose Codes</a>
 */
public enum SepaPurpose {

    ACCT("Kontenmanagement"),
    ADVA("Kreditzahlung"),
    AGRT("Landwirtschaftszahlung"),
    AIRB("Luftfracht"),
    ALMY("Unterhaltszahlung"),
    ANNI("Rente"),
    ANTS("Anästhesie-Dienstleistung"),
    AREN("Forderungseingang"),
    BECH("Kinderbeihilfe"),
    BENE("Schwerbeh./Arb.unfäh.Rente"),
    BEXP("Geschäftskosten"),
    BOCE("Buchung zu erfolgtem Umtausch"),
    BONU("Bonuszahlung"),
    BUSB("Bus"),
    CASH("Dispositionszahlung"),
    CBFF("Vermögenswirksame Leistungen"),
    CBTV("Kabel-TV-Rechnung"),
    CCRD("Kreditkartenzahlung"),
    CDBL("Kreditkartenabrechnung"),
    CDCB(" POS-Zahlung mit Cashback"),
    CDCD("Barauszahlung"),
    CDOC("Gutschrift aus Glückspiel"),
    CDQC("Gutschrift für Bargeldersatz"),
    CFEE("Stornogebühr"),
    CHAR("Spende"),
    CLPR("Ablösung Autodarlehen"),
    CMDT("Wirtschaftsgüter"),
    COLL("Einzug"),
    COMC("Warenkredit"),
    COMM("Provision"),
    COMT("Zahlung zu Gunsten Dritter"),
    COST("Kosten"),
    CPYR("Kopierrechte"),
    CSDB("Bareinzahlung"),
    CSLP("Firmensozialkredit-Zahlung an die Bank"),
    CVCF("Genesung/Vorsorge"),
    DBTC("Lastschriftzahlung"),
    DCRD("Debitkartenzahlung"),
    DEPT("Einzahlung"),
    DERI("Derivate"),
    DIVD("Dividenden"),
    DMEQ("medizinische Anlagen"),
    DNTS("Zahnservices"),
    ELEC("Stromrechnung"),
    ENRG("Energie"),
    ESTX("Vermögenssteuer"),
    FERB("Fähre"),
    FREX("Devisenverkehr"),
    GASB("Gas-Rechnung"),
    GDDS("An- und Verkauf von Waren"),
    GDSV("Kauf von Waren und Service mit Rückvergütung"),
    GOVI("Versicherung von Behörden"),
    GOVT("staatliche Zahlung"),
    GSCB("Rückvergütung aus Ankauf von Waren und Service"),
    HEDG("Deckungsgeschäft"),
    HLRP("Ablösung Hausdarlehen"),
    HLTC("Gesundheitsvorsorge"),
    HLTI("Krankenversicherung"),
    HSPC("Krankenhausvorsorge"),
    HSTX("Haus- und Grundsteuer"),
    ICCP("garantierte Kreditkartenzahlung"),
    ICRF("Kurzzeitbetreuung"),
    IDCP("garantierte Debitkartenzahlung"),
    IHRP("Ratenkauf"),
    INPC("Fahrzeugversicherung"),
    INSM("Abzahlung"),
    INSU("Premium-Versicherung"),
    INTC("Konzernzahlung"),
    INTE("Zinsen"),
    INTX("Einkommenssteuer"),
    LBRI("Arbeitslosenversicherung"),
    LICF("Lizenzgebühr"),
    LIFI("Lebensversicherung"),
    LIMA("Liquiditätsmanagement"),
    LOAN("General-Kredit"),
    LOAR("Ablösung Kredit"),
    LTCF("Langzeitbetreuung"),
    MDCS("Medizin-Service"),
    MSVC("unterschied. Dienstleistung"),
    NETT("Spitzenausgleich"),
    NITX("Einkommenssteuer"),
    NOWS("nicht näher definiert"),
    NWCH("Netzwerk-Abbuchung"),
    NWCM("Netzwerk-Kommunikation"),
    OFEE("Eröffnungsgebühr"),
    OTHR("andere"),
    OTLC("andere Telecom-Rechnungen"),
    PADD("authorisierte Verfügung"),
    PAYR("Gehaltszahlung"),
    PENS("Pensionszahlung"),
    PHON("Telefon-Rechnung"),
    POPE("Zahlung am Point of Sale"),
    PPTI("Hausratversicherung"),
    PRCP("Preiszahlung"),
    PRME("Edelmetal"),
    PTSP("Zahlungskonditionen"),
    RCKE("Wiedervorgelegte Scheckzahlung"),
    RCPT("akzeptierte Zahlung"),
    REFU("Gutschrift / Rücküberweisung"),
    RENT("Miete"),
    RINP("Ratenzahlung"),
    RLWY("Eisenbahn"),
    ROYA("Tantiemen"),
    SALA("Gehaltszahlung"),
    SAVG("Spareinlagen / Renten"),
    SCVE("Kauf und Verkauf von Dienstleistungen"),
    SECU("Sicherheiten/Wertpapiere"),
    SSBE("Sozialversicherungsbeihilfe"),
    STDY("Studium"),
    SUBS("Abo/Beitrag"),
    SUPP("Lieferantenzahlung"),
    TAXS("Steuerzahlung"),
    TELI("Telefonisch veranlasste Transaktion"),
    TRAD("Handelsgeschäfte"),
    TREA("Steuererstattung"),
    TRFD("Treuhänderfond"),
    VATX("Mehrwert-/Umsatzsteuer"),
    VIEW("Augenvorsorge"),
    WEBI("Internet basierte Transaktion"),
    WHLD("Kapitalertrags- / Quellensteuer"),
    WTER("Wasser-Rechnung");

    private final String germanDescription;

    SepaPurpose(String germanDescription) {
        this.germanDescription = germanDescription;
    }

    public String getGermanDescription() {
        return germanDescription;
    }
}
